### PR TITLE
adds types to exports to resolve tsc error

### PR DESCRIPTION
**Pull request by devo-wm**
Helps to resolve the following build error:

```console
$ tsc && vite build
src/hooks/auth.ts:1:31 - error TS7016: Could not find a declaration file for module 'react-query-auth'. '/path/to/project/node_modules/react-query-auth/dist/index.mjs' implicitly has an 'any' type.
  There are types at '/path/to/project/node_modules/react-query-auth/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'react-query-auth' library may need to update its package.json or typings.

1 import { configureAuth } from "react-query-auth";
                                ~~~~~~~~~~~~~~~~~~


Found 1 error in src/hooks/auth.ts:1
```

### CODE REVIEW

**Review by josermarinr — APPROVED** [review]

**Comment by dahsameer** [comment]
Will this be merged anytime soon?

**Comment by goktugs** [comment]
Can you merge this bud? @alan2207

**Comment by alan2207** [comment]
Hey folks, latest updates published with the latest version - 2.4.0

**Comment by goktugs** [comment]
@alan2207 hi sorry for bother again but im currently facing with strange issue. im currently updating version to 2.4.0. i deleted package-lock.json and node_modules then i did npm install.

`{
  "name": "test-app",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.9.0",
    "@radix-ui/react-icons": "^1.3.0",
    "@radix-ui/react-label": "^2.1.0",
    "@radix-ui/react-select": "^2.1.1",
    "@radix-ui/react-slot": "^1.1.0",
    "@tanstack/react-query": "^5.52.1",
    "axios": "^1.7.5",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "framer-motion": "^11.3.30",
    "lucide-react": "^0.435.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-error-boundary": "^4.0.13",
    "react-hook-form": "^7.53.0",
    "react-query-auth": "^2.4.0",
    "react-router-dom": "^6.26.1",
    "tailwind-merge": "^2.5.2",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@eslint/js": "^9.9.0",
    "@types/node": "^22.5.0",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.1",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.9.0",
    "eslint-plugin-react-hooks": "^5.1.0-rc.0",
    "eslint-plugin-react-refresh": "^0.4.9",
    "globals": "^15.9.0",
    "postcss": "^8.4.41",
    "tailwindcss": "^3.4.10",
    "typescript": "^5.5.3",
    "typescript-eslint": "^8.0.1",
    "vite": "^5.4.1"
  }
}
`

however it still give error. i checked package.json for your package.


`{
  "name": "react-query-auth",
  "version": "2.4.0",
  "author": "alan2207",
  "license": "MIT",
  "repository": "alan2207/react-query-auth",
  "main": "./dist/index.mjs",
  "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
  "files": [
    "dist",
    "src"
  ],
  "exports": {
    "require": "./dist/index.js",
    "import": "./dist/index.mjs"
  },
  "engines": {
    "node": ">=16"
  },
  "scripts": {
    "dev": "tsup src/index.tsx --watch",
    "build": "tsup src/index.tsx",
    "test": "jest",
    "lint": "eslint --fix ./src",
    "size": "size-limit"
  },
  "peerDependencies": {
    "@tanstack/react-query": ">=4.24.6",
    "react": ">=16.8.0"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
  },
  "size-limit": [
    {
      "path": "dist/index.mjs",
      "limit": "10 KB"
    },
    {
      "path": "dist/index.js",
      "limit": "10 KB"
    }
  ],
  "devDependencies": {
    "@size-limit/preset-small-lib": "^8.2.4",
    "@tanstack/react-query": "^5.7.2",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/react-hooks": "^8.0.1",
    "@types/react": "^18.0.28",
    "@types/react-dom": "^18.0.11",
    "@typescript-eslint/eslint-plugin": "^5.52.0",
    "@typescript-eslint/parser": "^5.52.0",
    "eslint": "^8.34.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-react": "^7.32.2",
    "husky": "^8.0.3",
    "jest": "^29.4.3",
    "jest-environment-jsdom": "^29.4.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "size-limit": "^8.2.4",
    "ts-jest": "^29.0.5",
    "tsup": "^6.6.3",
    "typescript": "^4.9.5"
  }
}
`

as you can see version is changed but exports still not updated. do you know why?

**Comment by alan2207** [comment]
@goktugs , can you share your `tsconfig.json` here?

**Comment by goktugs** [comment]
> @goktugs , can you share your `tsconfig.json` here?

Sorry for late reply

image

**Comment by alan2207** [comment]
@goktugs Can you try changing `jsx` to `preserve`?

**Comment by goktugs** [comment]
> @goktugs Can you try changing `jsx` to `preserve`?

i changed jsx at tsconfig.app.json to preserve. then i deleted package.lock and node_modules theen npm install. nothing changed

**Comment by alan2207** [comment]
@goktugs can you share a repro?

**Comment by dahsameer** [comment]
@alan2207 , seems like this change didn't make it to npm package.
image

**Comment by alan2207** [comment]
Can you try again with `2.4.1`?

**Comment by goktugs** [comment]
> Can you try again with `2.4.1`?

Thank you so much its working now

**Pull request merged**
